spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret : ${JWT_SECRET}
    expirationtime : ${JWT_EXPIRATIONTIME}